# Generated by Django 5.0 on 2024-01-02 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
