# Generated by Django 5.0 on 2024-01-03 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
