# Generated by Django 5.0 on 2024-01-03 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_members_member_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
