# Generated by Django 5.0 on 2024-01-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
    ]
